"""add failure_reason to goals

Revision ID: 418a33be09c2
Revises: 2f38cd0d5501
Create Date: 2025-12-23 03:22:06.605911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418a33be09c2'
down_revision: Union[str, Sequence[str], None] = '2f38cd0d5501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('failure_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'failure_reason')
    # ### end Alembic commands ###
