"""add_failed_column_to_milestones

Revision ID: 4c51bc27cf8e
Revises: 418a33be09c2
Create Date: 2025-12-29 14:09:36.647132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c51bc27cf8e'
down_revision: Union[str, Sequence[str], None] = '418a33be09c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('failed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'failed')
    # ### end Alembic commands ###
